// Code generated by sqlc. DO NOT EDIT.

package user

import (
	"database/sql"

	"github.com/google/uuid"
)

type Users struct {
	TableID   sql.NullInt64 `json:"tableID"`
	UserID    uuid.UUID     `json:"userID"`
	Email     string        `json:"email"`
	FirstName string        `json:"firstName"`
	LastName  string        `json:"lastName"`
	CreatedAt sql.NullTime  `json:"createdAt"`
}
