// Code generated by sqlc. DO NOT EDIT.

package user

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	DeleteUserByEmail(ctx context.Context, email string) error
	DeleteUserByID(ctx context.Context, userID uuid.UUID) error
	GetUserByEmail(ctx context.Context, email string) (Users, error)
	GetUserByID(ctx context.Context, userID uuid.UUID) (Users, error)
	ListPaginatedUsers(ctx context.Context, arg ListPaginatedUsersParams) ([]Users, error)
	ListUsers(ctx context.Context) ([]Users, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (Users, error)
}

var _ Querier = (*Queries)(nil)
