// Code generated by sqlc. DO NOT EDIT.

package task

import (
	"database/sql"

	"github.com/google/uuid"
)

type Tasks struct {
	TableID        sql.NullInt64 `json:"tableID"`
	TaskID         uuid.UUID     `json:"taskID"`
	UserID         uuid.UUID     `json:"userID"`
	DataRange      interface{}   `json:"dataRange"`
	ReminderPeriod sql.NullInt64 `json:"reminderPeriod"`
	CreatedAt      sql.NullTime  `json:"createdAt"`
}

type Users struct {
	TableID   sql.NullInt64 `json:"tableID"`
	UserID    uuid.UUID     `json:"userID"`
	Email     string        `json:"email"`
	FirstName string        `json:"firstName"`
	LastName  string        `json:"lastName"`
	CreatedAt sql.NullTime  `json:"createdAt"`
}
