// Code generated by sqlc. DO NOT EDIT.

package task

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateTask(ctx context.Context, arg CreateTaskParams) (Tasks, error)
	DeleteTask(ctx context.Context, userID uuid.UUID) error
	GetPaginatedTasksByUserEmail(ctx context.Context, arg GetPaginatedTasksByUserEmailParams) ([]GetPaginatedTasksByUserEmailRow, error)
	GetPaginatedTasksByUserID(ctx context.Context, arg GetPaginatedTasksByUserIDParams) ([]GetPaginatedTasksByUserIDRow, error)
	GetTask(ctx context.Context, taskID uuid.UUID) (Tasks, error)
	GetTasksByUserEmail(ctx context.Context) ([]GetTasksByUserEmailRow, error)
	GetTasksByUserID(ctx context.Context) ([]GetTasksByUserIDRow, error)
	ListPaginatedTasks(ctx context.Context, arg ListPaginatedTasksParams) ([]Tasks, error)
	ListTasks(ctx context.Context) ([]Tasks, error)
}

var _ Querier = (*Queries)(nil)
